### ISSUE TITLE
Doesnt work at all on my side

### ISSUE THREAD

**Issue by aristoprats** [aristoprats/bloop#2]
script initializes on both host and guest side

guest can connect, host acknowledges connection
guest inputs character,
script crashes host side with error:
' ' '
Waiting for Connection
Connection to  127.0.0.1  initialized at  52042
Guests input was
Unhandled exception in thread started by <function send_recieve at 0x0097A6A8>
Traceback (most recent call last):
  File "C:\Users\prats\Documents\Comp SCi\Python Lulz\Projects\Network Comms Project\harry code.py", line 42, in send_recieve
    if (input.lower()[0] == 'z'):
IndexError: string index out of range
' ' '

and hangs on guest side

Also still has the aids output on guest terminal for whatever reason

**Comment by harryto** [comment]
oh i didnt fix the exit when fixing the output problem 
also, ```, not '''

**Comment by harryto** [comment]
hmm, put in `print(data)` in your send_recieve(), see what comes out, maybe the data my computer sends is different from what your computer sends when using telnet. 

the data i get is this usually 
```
b'input content\r\n'
```
