### ISSUE TITLE
I forgot to name this something relevant

### ISSUE THREAD

**Issue by aristoprats** [aristoprats/bloop#3]
This is essentially the same script as computer_receive_from_ext.py 

but with the functionality of send and receive separated. Saving this as a separate file because im going to try and thread the two processes to be asynchronous and independent of each other but will 999/1000 screw this up so yeh.

changes:

var port has been changed (my port 5555 was occupied) to 5551

The functions are commented out at the moment, to activate either one remove its triple-quotes AND the corresponding start_new_thread call as denoted by the (n) after the comment out

**Comment by harryto** [comment]
So what's the issue?
